#!/bin/bash
POSIXLY_CORRECT=yes

lastFlag=0
command=list
commandSet=0
after=""
afterSet=0
before=""
beforeSet=0
user=""
currency=()
output=""
margin=${XTF_PROFIT:-20}

setCommand(){

  case $1 in
    list)
      command=list
      ((commandSet++))
      return 0
    ;;
    
    list-currency)
      command=list-currency
      ((commandSet++))
      return 0
    ;;

    status)
      command=status
      ((commandSet++))
      return 0
    ;;

    profit)
      command=profit
      ((commandSet++))
      return 0
    ;;
  esac

  return 1
}

setFilters(){
  case $1 in
    -a)
      lastFlag=1
    ;;

    -b)
      lastFlag=2
    ;;

    -c)
      lastFlag=3
    ;;

    *)
      lastFlag=0
    ;;
  esac
}

filterUser(){
  output=$(echo "$output" | grep -h "$user")
}

filterCurrency() {
  if [ "$currency" == "" ]; then
    return
  fi

  output=$(echo "$output" | awk -F';' -v currency="${currency[@]}" '
    BEGIN {
        split(currency, arr, " ");
        for (i in arr) {
            currencies[arr[i]] = 1;
        }
    }
    {
        if ($3 in currencies) {
            print $0;
        }
    }
  ')
}

# TODO refactor
filterAfter(){
  if [ "$after" == "" ]; then 
    return
  fi

  local IFS=$'\n'
  for line in $output; do
    date=$(echo $line | awk -F ';' '{printf "%s", $2}')
    isAfter=$(echo "$date" | awk -v afterDate="$after" '{split($0, date, /[- :]/);
      isValid = 1;

      if (date[1] > substr(afterDate, 1, 4)) {
        isValid = 0;
      } else if (date[1] == substr(afterDate, 1, 4) && date[2] > substr(afterDate, 6, 2)) {
        isValid = 0;
      } else if (date[1] == substr(afterDate, 1, 4) && date[2] == substr(afterDate, 6, 2) && date[3] > substr(afterDate, 9, 2)) {
        isValid = 0;
      } else if (date[1] == substr(afterDate, 1, 4) && date[2] == substr(afterDate, 6, 2) && date[3] == substr(afterDate, 9, 2) && date[4] > substr(afterDate, 12, 2)) {
        isValid = 0;
      } else if (date[1] == substr(afterDate, 1, 4) && date[2] == substr(afterDate, 6, 2) && date[3] == substr(afterDate, 9, 2) && date[4] == substr(afterDate, 12, 2) && date[5] > substr(afterDate, 15, 2)) {
        isValid = 0;
      } else if (date[1] == substr(afterDate, 1, 4) && date[2] == substr(afterDate, 6, 2) && date[3] == substr(afterDate, 9, 2) && date[4] == substr(afterDate, 12, 2) && date[5] == substr(afterDate, 15, 2) && date[6] >= substr(afterDate, 18, 2)) {
        isValid = 0;
      }

      print isValid;
    }')

    if [ $isAfter == 1 ]; then
      output=$(echo "$output" | grep -v "$date")
    fi
  done
}

# TODO refactor
filterBefore(){
  if [ "$before" == "" ]; then 
    return
  fi

  local IFS=$'\n'
  for line in $output; do
    date=$(echo $line | awk -F ';' '{printf "%s", $2}')
    isBefore=$(echo "$date" | awk -v beforeDate="$before" '{split($0, date, /[- :]/);
      isValid = 0;

      if (date[1] > substr(beforeDate, 1, 4)) {
        isValid = 1;
      } else if (date[1] == substr(beforeDate, 1, 4) && date[2] > substr(beforeDate, 6, 2)) {
        isValid = 1;
      } else if (date[1] == substr(beforeDate, 1, 4) && date[2] == substr(beforeDate, 6, 2) && date[3] > substr(beforeDate, 9, 2)) {
        isValid = 1;
      } else if (date[1] == substr(beforeDate, 1, 4) && date[2] == substr(beforeDate, 6, 2) && date[3] == substr(beforeDate, 9, 2) && date[4] > substr(beforeDate, 12, 2)) {
        isValid = 1;
      } else if (date[1] == substr(beforeDate, 1, 4) && date[2] == substr(beforeDate, 6, 2) && date[3] == substr(beforeDate, 9, 2) && date[4] == substr(beforeDate, 12, 2) && date[5] > substr(beforeDate, 15, 2)) {
        isValid = 1;
      } else if (date[1] == substr(beforeDate, 1, 4) && date[2] == substr(beforeDate, 6, 2) && date[3] == substr(beforeDate, 9, 2) && date[4] == substr(beforeDate, 12, 2) && date[5] == substr(beforeDate, 15, 2) && date[6] >= substr(beforeDate, 18, 2)) {
        isValid = 1;
      }

      print isValid;
    }')

    if [ $isBefore == 1 ]; then
      output=$(echo "$output" | grep -v "$date")
    fi
  done
}

listFunc(){
  echo "$output"
}

listCurrencyFunc(){
  echo "$output" | awk -F ';' '{printf "%s\n", $3}' | sort | uniq
}

statusFunc() {
  currencyNames=$(echo "$output" | awk -F ';' '{printf "%s\n", $3}' | sort | uniq)

  for name in $currencyNames; do
    values=$(echo "$output" | grep -h "${name}" | awk -F ';' '{printf "%s ", $4}')
    sum=$(echo "$values" | awk '{ sum = 0; for(i=1; i<=NF; i++) sum += $i; printf "%.4f\n", sum}')
    echo "$name : $sum"
  done
}

profitFunc() {
  currencyNames=$(echo "$output" | awk -F ';' '{printf "%s\n", $3}' | sort | uniq)

  for name in $currencyNames; do
    values=$(echo "$output" | grep -h "${name}" | awk -F ';' '{printf "%s ", $4}')
    sum=$(echo "$values" | awk '{ sum = 0; for(i=1; i<=NF; i++) sum += $i; printf "%.4f\n", sum}')
    if (( $(echo "$sum < 0" | bc -l) )); then
      echo "$name : $sum"
    else
      sum=$(echo "scale=4; $sum * ((100 + $margin) / 100)" | bc)
      echo "$name : $sum"
    fi
  done
}

if [ "$#" -lt 2 ]; then
  exit 1
fi

for arg in "$@"; do
  if [ $lastFlag -eq 1 ]; then
    after=$arg
    lastFlag=0
    ((afterSet++))
    continue
  elif [ $lastFlag -eq 2 ]; then
    before=$arg
    lastFlag=0
    ((beforeSet++))
    continue
  elif [ $lastFlag -eq 3 ]; then
    currency="$arg ${currency[@]}"
    lastFlag=0
    continue
  fi

  setCommand $arg
  if [ $? == 0 ]; then
    continue
  fi

  setFilters $arg
  if [ $lastFlag != 0 ]; then
    continue
  fi

  if [ "$user" == "" ]; then
    user=$arg
  else
    if [ ! -e "$arg" ]; then
      exit 1
    fi

    if echo "$arg" | grep -q ".gz"; then
      output+=$(gzip -cd "$arg")
    else
      output+=$(cat "$arg" | tr -d '\0')$'\n'
    fi
  fi  
done


if [ "$user" == "" ]; then
  exit 1
fi

if [ "$commandSet" -gt 1 ]; then
  exit 1
fi

if [ "$afterSet" -gt 1 ]; then
  exit 1
fi

if [ "$beforeSet" -gt 1 ]; then
  exit 1
fi

filterUser
filterAfter
filterBefore
filterCurrency

case $command in
    list)
      listFunc
    ;;
    
    list-currency)
      listCurrencyFunc
    ;;

    status)
      statusFunc
    ;;

    profit)
      profitFunc
    ;;
esac